project:
  type: website
  output-dir: docs

website:
  title: "MYBLOG"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jul1ette-d/
      
format:
  html:
    theme: cosmo
    css: styles.css





