project:
  type: website
  output-dir: docs

website:
  title: "MYBLOG"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jul1ette-d/
      - icon: linkedin
        href: https://www.linkedin.com/in/juliette-degoul-68839a20/
      
format:
  html:
    theme: cosmo
    css: styles.css





